name: deploy
on:
  push:
    branches: [main]
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: "16.14.0"

      - name: build tools
        run: npm -g install windows-build-tools

      - name: install-dependencies
        run: yarn install

      - name: electron
        run: yarn rebuild --abi=93

      - name: electron build
        run: yarn build-electron-win
