name: deploy
on:
  push:
    branches: [main]
jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: "16.14.0"

      - name: install-dependencies
        run: yarn install

      - name: run test
        run: yarn test

      - name: build
        run: yarn build

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: "16.14.0"

      - name: install-dependencies
        run: yarn install

      - name: run test
        run: yarn test

      - name: build
        run: yarn build

  build-windows:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: "16.14.0"

      - name: install-dependencies
        run: yarn install

      - name: run test
        run: yarn test

      - name: build
        run: yarn build

  build-electron-windows:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: "16.14.0"

      - name: install-dependencies
        run: yarn install

      - name: electron rebuild
        run: yarn rebuild --abi=93

      - name: build
        run: yarn build-electron-win
