name: deploy
on:
  push:
    branches: [main]
jobs:
  build-mac:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: "16.14.0"

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: install-dependencies
        run: yarn install

      - name: electron
        run: yarn rebuild --abi=93

      - name: electron build
        run: yarn build-electron-mac
